language: c++
matrix:
  include:
  - os: linux
    sudo: required
  - os: osx

env:
  global:
  - CCACHE_CPP2=yes
  - CCACHE_SLOPPINESS=time_macros

cache:
  ccache: true

if: tag IS present

install:
  - |-
  # Install ccache (if necessary) and set it up.
  if [[ "$TRAVIS_OS_NAME" == "osx" && ! $(which ccache) ]]; then
    brew install ccache
    export PATH="/usr/local/opt/ccache/libexec:$PATH"
  fi
  ccache --version | head -n 1
  ccache --max-size=5G
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH="$(pwd)/depot_tools:$PATH"
  - fetch v8
  - git fetch origin ${TRAVIS_TAG}
  - git checkout ${TRAVIS_TAG}
  - gclient sync

script:
  - ./compile_v8.sh
